# api-related fields
api:
  # The port on which the API will be exposed (default:3001)
  port: 3001

  # Enable/disable development CORS
  dev-cors: true

  # Allowed hosts for HTTP API development CORS
  dev-cors-host: "*"

# database fields
db:
  # Database host
  host: "localhost"

  # Database port
  port: 5432

  # Database sslmode
  sslmode: "disable"

  # Database name
  dbname: "simulator"

  # Database user (also allowed via PG_USER env var)
  user: "core"

  # Database password
  password: "password"

  # Auto run database migrations
  automigrate: true

# Modules
sow:

  # CoinPaprika price scraper
  paprika:

    # Coin to fetch pricing data for
    coinid: eth-ethereum

    # Price intervals
    interval: 5m

    # Start of pricing data
    start: 1 jan 2020

    # End of pricing data
    stop: 31 dec 2020

# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=trace"
